# -*- coding: utf-8 -*-
"""get_data_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d5XlYSO97pKI1a2AmY2oxj_3Phhc70Ng
"""

import requests

def make_api_call(resource):
    ENDPOINT = "https://dummyjson.com/"
    results_picked = 0
    total_results = 100 #We don't know yet, but we need to initialize
    all_data = []
    while results_picked < total_results:
        response = requests.get(f"{ENDPOINT}{resource}", params = {"skip" : results_picked})
        if response.status_code == 200:
            data = response.json()
            rows = data.get(resource)
            all_data += rows #concatening the two lists
            total_results = data.get("total")
            results_picked += len(rows) #to skip them in the next call
        else:
            raise Exception(response.text)
    return all_data

carts_data = make_api_call("carts")
users_data = make_api_call("users")
# users_address
products_data = make_api_call("products")
comments_data = make_api_call("comments")
posts_data = make_api_call("posts")

import json

def download_json(data, resource_name):
    file_path = f"{resource_name}.json"
    with open(file_path, "w") as file:
        file.write("\n".join([json.dumps(row) for row in data]))

download_json(carts_data, "carts")
download_json(users_data, "users")
download_json(posts_data, "posts")
download_json(products_data, "products")
download_json(comments_data, "comments")